// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {jobs} from '../models';

export function CancelTranscription():Promise<void>;

export function CurrentJob():Promise<domain.Job>;

export function DownloadWhisperModel(arg1:string):Promise<domain.Settings>;

export function GetDiagnostics():Promise<domain.DiagnosticReport>;

export function GetSettings():Promise<domain.Settings>;

export function GetWhisperModels():Promise<Array<domain.WhisperModelOption>>;

export function InstallOrFixDiagnostic(arg1:string):Promise<domain.DiagnosticReport>;

export function JobEvents(arg1:number):Promise<Array<jobs.Event>>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function PickInputFile():Promise<string>;

export function PickModelDirectory():Promise<string>;

export function PickModelFile():Promise<string>;

export function PickOutputDirectory():Promise<string>;

export function RefreshDiagnostics():Promise<domain.DiagnosticReport>;

export function Run():Promise<void>;

export function SaveSettings(arg1:domain.Settings):Promise<domain.Settings>;

export function StartTranscription(arg1:string):Promise<domain.Job>;
