// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTranscription() {
  return window['go']['bootstrap']['App']['CancelTranscription']();
}

export function CurrentJob() {
  return window['go']['bootstrap']['App']['CurrentJob']();
}

export function DownloadWhisperModel(arg1) {
  return window['go']['bootstrap']['App']['DownloadWhisperModel'](arg1);
}

export function GetDiagnostics() {
  return window['go']['bootstrap']['App']['GetDiagnostics']();
}

export function GetSettings() {
  return window['go']['bootstrap']['App']['GetSettings']();
}

export function GetWhisperModels() {
  return window['go']['bootstrap']['App']['GetWhisperModels']();
}

export function InstallOrFixDiagnostic(arg1) {
  return window['go']['bootstrap']['App']['InstallOrFixDiagnostic'](arg1);
}

export function JobEvents(arg1) {
  return window['go']['bootstrap']['App']['JobEvents'](arg1);
}

export function OpenOutputFolder(arg1) {
  return window['go']['bootstrap']['App']['OpenOutputFolder'](arg1);
}

export function PickInputFile() {
  return window['go']['bootstrap']['App']['PickInputFile']();
}

export function PickModelDirectory() {
  return window['go']['bootstrap']['App']['PickModelDirectory']();
}

export function PickModelFile() {
  return window['go']['bootstrap']['App']['PickModelFile']();
}

export function PickOutputDirectory() {
  return window['go']['bootstrap']['App']['PickOutputDirectory']();
}

export function RefreshDiagnostics() {
  return window['go']['bootstrap']['App']['RefreshDiagnostics']();
}

export function Run() {
  return window['go']['bootstrap']['App']['Run']();
}

export function SaveSettings(arg1) {
  return window['go']['bootstrap']['App']['SaveSettings'](arg1);
}

export function StartTranscription(arg1) {
  return window['go']['bootstrap']['App']['StartTranscription'](arg1);
}
